plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.siedlar.nexusprank'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.siedlar.nexusprank'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.1.0-v11'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
